# Generated by Django 4.2.9 on 2024-02-23 22:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalPlannerAPI', '0002_rename_date_event_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='events_attending', to='PersonalPlannerAPI.ppuser'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
